In [2]:
import tensorflow as tf

In [4]:
x1 = tf.constant([1,2,3,4,5])
x2 = tf.constant([2,4,6,8,10])

#Multiply
result = tf.multiply(x1,x2)
print(result)

tf.Tensor([ 2  8 18 32 50], shape=(5,), dtype=int32)


In [6]:
x1 = tf.constant([1,2,3,4,5])
x2 = tf.constant([2,4,6,8,10])

#Multiply
result = tf.add(x1,x2)
print(result)

tf.Tensor([ 3  6  9 12 15], shape=(5,), dtype=int32)


In [7]:
x1 = tf.constant([1,2,3,4,5])
x2 = tf.constant([2,4,6,8,10])

#Multiply
result = tf.subtract(x1,x2)
print(result)

tf.Tensor([-1 -2 -3 -4 -5], shape=(5,), dtype=int32)


In [ ]:
import pandas as pd
import numpy as np

#make numpy values easier to read.
np.set_printoptions(precision = 3, suppress = True)

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import preprocessing

abc_train=pd.read_csv('https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv',
                       names = ["Length", "Diameter", "Height", "Whole weight", 
                                "shucked weight", "Viscera weight", "Shell weight", "Age"])

abc_train.head()

In [11]:
pip install tensorflow-datasets

  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=f42d5178cf535922d518da3a440e6b0c2fb502b7c4a89277dd5af8203be98b6f
  Stored in directory: c:\users\tls\appdata\local\pip\cache\wheels\8e\70\28\3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21494 sha256=c9527dc5641af4d514ae62e6df6f34ce7ffbc713866d440afb185e0461284b74
  Stored in directory: c:\users\tls\appdata\local\pip\cache\wheels\54\aa\01\724885182f93150035a2a91bce34a12877e8067a97baaf5dc8
Successfully built future promise
Note: you may need to restart the kernel to use updated packages.


In [12]:
import tensorflow_datasets as tfds

In [13]:
#available datasets
tfds.list_builders()

['abstract_reasoning',
 'accentdb',
 'aeslc',
 'aflw2k3d',
 'ag_news_subset',
 'ai2_arc',
 'ai2_arc_with_ir',
 'amazon_us_reviews',
 'anli',
 'arc',
 'bair_robot_pushing_small',
 'bccd',
 'beans',
 'big_patent',
 'bigearthnet',
 'billsum',
 'binarized_mnist',
 'binary_alpha_digits',
 'blimp',
 'bool_q',
 'c4',
 'caltech101',
 'caltech_birds2010',
 'caltech_birds2011',
 'cars196',
 'cassava',
 'cats_vs_dogs',
 'celeb_a',
 'celeb_a_hq',
 'cfq',
 'cherry_blossoms',
 'chexpert',
 'cifar10',
 'cifar100',
 'cifar10_1',
 'cifar10_corrupted',
 'citrus_leaves',
 'cityscapes',
 'civil_comments',
 'clevr',
 'clic',
 'clinc_oos',
 'cmaterdb',
 'cnn_dailymail',
 'coco',
 'coco_captions',
 'coil100',
 'colorectal_histology',
 'colorectal_histology_large',
 'common_voice',
 'coqa',
 'cos_e',
 'cosmos_qa',
 'covid19sum',
 'crema_d',
 'curated_breast_imaging_ddsm',
 'cycle_gan',
 'dart',
 'davis',
 'deep_weeds',
 'definite_pronoun_resolution',
 'dementiabank',
 'diabetic_retinopathy_detection',
 'div2k